server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_campus_hub
spring.datasource.username=postgres
spring.datasource.password=Pethmi123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
sensor.api.key=smart-campus-secret-2026