spring.application.name=booking-system

server.port=8080

spring.datasource.url=jdbc:h2:mem:smartcampusdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.oauth2.client.registration.google.client-id=933935718937-kk6o8b3fd7rm3vlu3lmccrldi3ls0t5e.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=GOCSPX-T0htYYWqY340n5NMOr8n1Xxksk
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.security.jwt.secret=replace-with-a-very-long-random-secret-key-at-least-32-bytes
app.security.jwt.expiration-minutes=120
app.security.allowed-origins=http://localhost:5173
app.security.admin-emails=admin@smartcampus.com
app.frontend.redirect-uri=http://localhost:5173/oauth/success
