spring.application.name=booking-system

server.port=8080


spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.security.jwt.secret=replace-with-a-very-long-random-secret-key-at-least-32-bytes
app.security.jwt.expiration-minutes=120
app.security.allowed-origins=http://localhost:5173
app.security.admin-emails=admin@smartcampus.com,thiyunuwan567@gmail.com
app.frontend.redirect-uri=http://localhost:5173/oauth/success

spring.mongodb.uri=mongodb://thiyunuwan567_db_user:dOCaP09kUgBoPshK@ac-bgxslep-shard-00-00.wyq22qs.mongodb.net:27017,ac-bgxslep-shard-00-01.wyq22qs.mongodb.net:27017,ac-bgxslep-shard-00-02.wyq22qs.mongodb.net:27017/smartcampusdb?authSource=admin&replicaSet=atlas-qlevlu-shard-0&retryWrites=true&w=majority&ssl=true
